### ISSUE TITLE
How to call an API?

### ISSUE THREAD

**Issue by yasinkavakli** [BenjaminWFox/nextjs-azureb2c-nextauth#6]
Hi Benjamin,

I've followed your tutorial and I was able to log in and log out from my NextJS app. Now I want to take this further and call my .NET Core WebAPI backend, which is also configured with Azure AD B2C. Do you have any experience with this? As far as I was able to see, I don't get any JWT Token from AzureADB2C so I don't know how I could call my backend (webapi) and pass in a token or id so that my backend can validate user that send the request.

Would appreciate any help 👍

**Comment by BenjaminWFox** [comment]
It is definitely not an obvious process. Take a look at my comment in this issue here which has links to relevant B2C documentation and a more extensive config for NextAuth: https://github.com/nextauthjs/next-auth/issues/468#issuecomment-721441387

**Comment by yasinkavakli** [comment]
Thank you, this helps and if I put a `console.log(token)` in line 91 I see the accessToken and refreshToken in the console, but I still get this error:

```
[next-auth][error][oauth_callback_handler_error] SyntaxError: Unexpected token e in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\developer\code\test\client\node_modules\next-auth\dist\lib\jwt.js:50:65)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\developer\code\test\client\node_modules\next-auth\dist\lib\jwt.js:22:103)
    at _next (C:\developer\code\test\client\node_modules\next-auth\dist\lib\jwt.js:24:194)
    at C:\developer\code\test\client\node_modules\next-auth\dist\lib\jwt.js:24:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\developer\code\test\client\node_modules\next-auth\dist\lib\jwt.js:24:97)
    at Object.encode (C:\developer\code\test\client\node_modules\next-auth\dist\lib\jwt.js:64:17)
    at C:\developer\code\test\client\node_modules\next-auth\dist\server\routes\callback.js:117:47
https://next-auth.js.org/errors#oauth_callback_handler_error
```

Not sure what I'm missing here.

**Comment by BenjaminWFox** [comment]
Were you able to figure out a resolution to this? It's not anything I've seen in my setup that I can remember.

**Comment by yasinkavakli** [comment]
Nope, I've ditched Azure ADB2C because there were couple of things that it doesn't support easily like roles. I'm thinking about Blazor vs Nextjs for my frontend with integrated authentication on my Webapi. Still haven't decided for 100% what I'm going to use. 
And I've seen that next-auth has an official AzureAdB2C provider merged into their canary release a day ago or so.
